apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hacktheplanet
spec:
  selector:
    matchLabels:
      app: hacktheplanet
  template:
    metadata:
      labels:
        app: hacktheplanet
    spec:
      hostPID: true
      volumes:
      - name: root
        hostPath:
          path: /root
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - name: hacktheplanet
        image: alpine
        volumeMounts:
        - name: root
          mountPath: /root
        command:
        - sh
        - -c
        - sleep infinity
        securityContext:
          privileged: true
      - name: web
        image: nginx

